'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert('Cars', [
      {
        id: 1,
        images: JSON.stringify(['lambo1.jpeg','lambo2.jpeg','lambo3.jpeg','lambo4.jpeg','lambo5.jpeg','lambo6.jpeg','lambo7.jpeg']),
        year: 2020,
        carModel_id: 541,
        brand_id: 32,
        user_id: 1,
        km: 10000,
        color: 'White',
        description: 'INTERIOR COLOR: Black w/ red stitching | ENGINE: V10',
        price: 253777,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        images: JSON.stringify(['ferrari1.jpeg','ferrari2.jpeg','ferrari3.jpeg','ferrari4.jpeg','ferrari5.jpeg','ferrari6.jpeg','ferrari7.jpeg']),
        year: 2013,
        carModel_id: 530,
        brand_id: 31,
        user_id: 1,
        km: 10000,
        color: 'Red',
        description: 'Engine: 6.3 L F140 FC V12',
        price: 325000,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 3,
        engine: '6.3L V-12',
        gas:'Premium gasoline',
        transmission: 'Automatic',
        doors: 2
      },
      {
        id: 3,
        images: JSON.stringify(['porsche1.png','porsche2.png','porsche3.png','porsche4.png','porsche5.png','porsche6.png','porsche7.png']),
        year: 2013,
        carModel_id: 399,
        brand_id: 18,
        user_id: 1,
        km: 10000,
        color: 'Black',
        description: 'coupe, turbo and eight-speed dual-clutch automatic transmission',
        price: 123000,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 2,
        engine: '3.8L',
        gas:'Premium gasoline',
        transmission: 'Manual',
        doors: 2,
      },
      {
        id: 4,
        images: JSON.stringify(['bugatti1.webp','bugatti2.webp','bugatti3.webp','bugatti4.webp','bugatti5.webp','bugatti6.webp']),
        year: 2023,
        carModel_id: 541,
        brand_id: 33,
        user_id: 1,
        km: 5000,
        color: 'Black',
        description: '8.0-liter 16-cylinder powerplant. four turbochargers that generate 1500 horsepower and 1180 pound-feet of torque.',
        price: 3000000,
        //bodyCar_id: 3,
        engine: '8.0L quad-turbocharged W16',
        gas:'Premium gasoline',
        transmission: 'Automatic',
        doors: 2,
      },
      {
        id: 5,
        images: JSON.stringify(['jaguar1.webp','jaguar2.webp','jaguar3.webp','jaguar4.webp','jaguar5.webp','jaguar6.webp']),
        year: 2015,
        carModel_id: 374,
        brand_id: 16,
        user_id: 1,
        km: 40000,
        color: 'Ornage',
        description: 'Powered by a supercharged 5.0-liter V8 linked to an eight-speed automatic transmission.',
        price: 50000,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 2,
        engine: 'Supercharged V6',
        gas:'Premium gasoline',
        transmission: 'Automatic',
        doors: 2,
      },
      {
        id: 6,
        images: JSON.stringify(['hg1.jpeg', 'hg2.jpeg', 'hg3.jpeg', 'hg4.jpeg', 'hg5.jpeg']),
        year: 2013,
        carModel_id: 282,
        brand_id: 10,
        user_id: 1,
        km: 200000,
        color: 'Gray',
        description: '3.8 Grand Touring RWD',
        price: 8500,
        onSale: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 2,
        engine: 'Lambda II V6',
        gas:'Regular gasoline',
        transmission: 'Automatic',
        doors: 2,
      },
      {
        id: 7,
        images: JSON.stringify(['ram1.jpg', 'ram2.jpg', 'ram3.jpg', 'ram4.jpg']),
        year: 2021,
        carModel_id: 551,
        brand_id: 34,
        user_id: 1,
        km: 40000,
        color: 'White',
        description: 'Tradesman Crew Cab LB DRW 4WD',
        price: 63000,
        onSale: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 5,
        engine: '6.4L V8',
        gas:'Regular gasoline',
        transmission: 'Automatic',
        doors: 4,
      },
      {
        id: 8,
        images: JSON.stringify(['tesla1.jpg', 'tesla2.jpg', 'tesla3.jpg', 'tesla4.jpg', 'tesla5.jpg']),
        year: 2021,
        carModel_id: 334,
        brand_id: 12,
        user_id: 1,
        km: 40000,
        color: 'White',
        description: 'Standard Range RWD',
        price: 38000,
        onSale: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 7,
        engine: 'Electric engine',
        gas:'Electricity',
        transmission: 'Automatic',
        doors: 4,
      },
      {
        id: 9,
        images: JSON.stringify(['bm41.webp','bm42.webp','bm43.webp','bm44.webp','bm45.webp','bm46.webp','bm47.webp','bm48.webp']),
        year: 2022,
        carModel_id: 170,
        brand_id: 6,
        user_id: 1,
        km: 15000,
        color: 'Black',
        description: 'Competition, 6-cyl, Turbo Gas, 3.0L',
        price: 78000,
        onSale: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 2,
        engine: '3.0L six-cylinde',
        gas:'Premium gasoline',
        transmission: 'Automatic',
        doors: 2,
      },
      {
        id: 10,
        images: JSON.stringify(['bmi1.webp','bmi2.webp','bmi3.webp','bmi4.webp','bmi5.webp','bmi6.webp','bmi7.webp','bmi8.webp']),
        year: 2016,
        carModel_id: 177,
        brand_id: 6,
        user_id: 1,
        km: 1000000,
        color: 'White',
        description: '6-cyl, Turbo Gas, 3.0L Engine',
        price: 31000,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 1,
        engine: '3.0L six-cylinde',
        gas: 'Premium gasoline',
        transmission: 'Automatic',
        doors: 2,

      },
      {
        id: 11,
        images: JSON.stringify(['bmx31.webp','bmx32.webp','bmx33.webp','bmx34.webp','bmx35.webp']),
        year: 2016,
        carModel_id: 154,
        brand_id: 6,
        user_id: 1,
        km: 100000,
        color: 'Blue',
        description: 'Model XDrive28i, 4-cyl, Turbo Gas, 2.0LEngine',
        price: 24000,
        onSale: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 4,
        engine: '2.0L TwinPower',
        gas:'Regular gasoline',
        transmission: 'Automatic',
        doors: 4,
      },
      {
        id: 12,
        images: JSON.stringify(['bmx61.webp','bmx62.webp','bmx63.webp','bmx64.webp','bmx65.webp',]),
        year: 2021,
        carModel_id: 159,
        brand_id: 6,
        user_id: 1,
        km: 40000,
        color: 'Black',
        description: 'Model M50i, 8-cyl, Turbo Gas, 4.4L Engine',
        price: 83000,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 2,
        engine: '3.0L TwinPower',
        gas: 'Premium gasoline',
        transmission: 'Automatic',
        doors: 4,
      },
      {
        id: 13,
        images: JSON.stringify(['bmxi1.webp', 'bmxi2.webp', 'bmxi3.webp', 'bmxi4.webp', 'bmxi5.webp']),
        year: 2020,
        carModel_id: 178,
        brand_id: 6,
        user_id: 1,
        km: 30000,
        color: 'Gray',
        description: 'Gran Coupe, 4-cyl, Turbo Gas, 2.0L Engine',
        price: 45000,
        onSale: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 2,
        engine: '2.0L TwinPower',
        gas:'Premium gasoline',
        transmission: 'Automatic',
        doors: 2,
      },
      {
        id: 14,
        images: JSON.stringify(['volkswagenGTI1.webp', 'volkswagenGTI2.webp', 'volkswagenGTI3.webp', 'volkswagenGTI4.webp', 'volkswagenGTI5.webp', 'volkswagenGTI6.webp','volkswagenGTI7.webp', 'volkswagenGTI8.webp']),
        year: 2017,
        carModel_id: 41,
        brand_id: 2,
        user_id: 1,
        km: 93341,
        color: 'Gray',
        description: 'sporty, well-equipped compact car with a turbocharged engine, sharp handling, and a comfortable interior',
        price: 25998,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 4,
        engine: '2.0L turbocharged',
        gas:'Premium gasoline',
        transmission: 'Manual',
        doors: 2,
      },
      {
        id: 15,
        images: JSON.stringify(['mustang.webp', 'mustang1.webp', 'mustang2.webp', 'mustang3.webp', 'mustang4.webp', 'mustang5.webp','mustang6.webp', 'mustang7.webp','mustang8.webp']),
        year: 2017,
        carModel_id: 61,
        brand_id: 3,
        user_id: 1,
        km: 11265,
        color: 'White',
        description: 'Its a formidable and exhilarating muscle car designed for spirited driving and track performance',
        price: 59998,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 2,
        engine: '5.2L v8',
        gas:'Premium gasoline',
        transmission: 'Manual',
        doors: 2,
      },
      {
        id: 16,
        images: JSON.stringify(['fraptor1.webp', 'fraptor2.webp', 'fraptor3.webp', 'fraptor4.webp', 'fraptor5.webp', 'fraptor6.webp','fraptor7.webp', 'fraptor8.webp']),
        year: 2020,
        carModel_id: 79,
        brand_id: 3,
        user_id: 1,
        km: 62764,
        color: 'grey',
        description: 'Aggressive styling with distinctive Raptor design cues',
        price: 61998,
        createdAt: new Date(),
        updatedAt: new Date(),
        //bodyCar_id: 5,
        engine: '3.5L v6',
        gas:'Regular gasoline',
        transmission: 'Automatic',
        doors: 4,
      },
      
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('Cars', null, {});
  }
};
